In [5]:
import torch
from torch import nn
from d2l import torch as d2l

## 1 二维互相关运算

In [6]:
def corr2d(X, K):  #@save K for kernel，X for local image 
    """计算二维互相关运算。"""
    h, w = K.shape 
    Y = torch.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i, j] = (X[i:i + h, j:j + w] * K).sum()
    return Y

## 2 二维卷积层

In [8]:
class conv2d(nn.Module):
    def __init__():
        super().__init__()
        self.weight = nn.Parameter(torch.rang(kernel_size))
        self.bias = nn.Parameter(torch.zeros(1))
    def forward(self, x):
        return corrd2d(x, self.weight) + self.bias

## 3 图像中物体边缘检测

In [10]:
X = torch.ones((6, 8))
X[:,2:6] = 0
print(X)

tensor([[1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.]])


In [12]:
K = torch.tensor([[1.0, -1.0]])
Y = corr2d(X, K)
print(Y) # 1 表示白色到黑色的边缘（左到右）， 只能检测垂直边缘

tensor([[ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.]])


## 4 通过数据学习核数组

In [15]:
conv2d = nn.Conv2d(1, 1, kernel_size=(1, 2), bias=False) # 初始化一个核，1->1通道及大小

X = X.reshape((1, 1, 6, 8)) # 通道维、批量大小维
Y = Y.reshape((1, 1, 6, 7))

for i in range(10):
    Y_hat = conv2d(X)
    l = (Y_hat - Y) ** 2
    conv2d.zero_grad()
    l.sum().backward()
    conv2d.weight.data[:] -= 3e-2 * conv2d.weight.grad # 简单的SGD
    if (i + 1) % 2 == 0:
        print(f'batch {i+1}, loss {l.sum():.3f}')

batch 2, loss 13.374
batch 4, loss 3.498
batch 6, loss 1.101
batch 8, loss 0.395
batch 10, loss 0.152


In [16]:
conv2d.weight.data.reshape((1, 2)) # 结果和[1, -1]差不多了

tensor([[ 1.0246, -0.9457]])