In [1]:
import numpy as np
import torch

## 1 创建 Tensor

In [2]:
x = torch.empty(5, 3) # 未初始化的
print(x)

tensor([[7.0692e+01, 6.0816e-43, 7.0692e+01],
        [6.0816e-43, 7.0707e+01, 6.0816e-43],
        [7.0707e+01, 6.0816e-43, 7.0704e+01],
        [6.0816e-43, 7.0704e+01, 6.0816e-43],
        [7.0717e+01, 6.0816e-43, 7.0717e+01]])


In [3]:
x = torch.rand(5, 3) # 随机初始化的
print(x)

tensor([[0.1081, 0.2539, 0.6131],
        [0.6491, 0.8413, 0.4000],
        [0.0845, 0.6805, 0.2759],
        [0.2890, 0.5556, 0.3897],
        [0.8954, 0.5275, 0.2817]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long) # 5x3的long型全0的
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3]) # 根据数据创建的，这是一个向量（一维）
print(x)

tensor([5.5000, 3.0000])


In [23]:
# 返回的tensor默认具有相同的torch.dtype和torch.device
y = x.new_ones(5, 3, dtype=torch.float64)
print(y)

y = torch.randn_like(x, dtype=torch.float)  # 指定新的数据类型
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([-1.3084, -0.2376])


In [7]:
print(x.size())
print(x.shape)
print(x.numel())

torch.Size([2])
torch.Size([2])
2


## 2 操作

### 算术操作

In [8]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x + y) # 形式一
print(torch.add(x, y)) # 形式二
print(y.add_(x)) # 形式三

tensor([[1.1313, 1.5622, 0.9919],
        [1.1230, 1.4280, 0.2899],
        [0.9636, 1.1940, 1.1247],
        [0.9707, 1.5208, 0.6872],
        [1.0495, 1.0271, 1.3564]])
tensor([[1.1313, 1.5622, 0.9919],
        [1.1230, 1.4280, 0.2899],
        [0.9636, 1.1940, 1.1247],
        [0.9707, 1.5208, 0.6872],
        [1.0495, 1.0271, 1.3564]])
tensor([[1.1313, 1.5622, 0.9919],
        [1.1230, 1.4280, 0.2899],
        [0.9636, 1.1940, 1.1247],
        [0.9707, 1.5208, 0.6872],
        [1.0495, 1.0271, 1.3564]])


In [9]:
print(torch.add(x, y))

tensor([[1.3019, 2.3251, 1.2454],
        [1.6681, 2.0890, 0.3749],
        [1.5745, 1.5889, 1.3296],
        [1.0088, 2.2503, 0.9171],
        [1.9841, 1.3135, 1.7795]])


### 索引

In [10]:
# 索引出来的结果与原数据共享内存
y = x[0, :]
y += 1
print(y)
print(x[0, :]) # 源tensor也被改了

tensor([1.1706, 1.7629, 1.2535])
tensor([1.1706, 1.7629, 1.2535])


### 改变形状

In [11]:
y = x.view(15)
z = x.view(-1, 5)  # -1所指的维度可以根据其他维度的值推出来
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [12]:
# Pytorch还提供了一个reshape()可以改变形状，
# 但是此函数并不能保证返回的是其拷贝，所以不推荐使用。
# 推荐先用clone创造一个副本然后再使用view
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[ 0.1706,  0.7629,  0.2535],
        [-0.4549, -0.3390, -0.9150],
        [-0.3891, -0.6051, -0.7951],
        [-0.9619, -0.2705, -0.7701],
        [-0.0655, -0.7137, -0.5769]])
tensor([1.1706, 1.7629, 1.2535, 0.5451, 0.6610, 0.0850, 0.6109, 0.3949, 0.2049,
        0.0381, 0.7295, 0.2299, 0.9345, 0.2863, 0.4231])


In [13]:
x = torch.randn(1)
print(x)
print(x.item()) # 转换成一个Python number，非numpy, 且只能是标量（0维）

tensor([-0.5456])
-0.5455626845359802


### 线性代数

## 3 广播机制

In [14]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


## 4 运算的内存开销

In [15]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
id_now = id(y)
print(id_now == id_before) # False 

False


In [16]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
id_now = id(y)
print(id_now == id_before) # True

True


In [17]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x) 这里y+=x 和 y=y+x 不等效
print(id(y) == id_before) # True

True


## 5 Tensor和NumPy相互转换

In [18]:
a = np.array([1,1,1,1])
b = torch.from_numpy(a)

### Tensor 转 NumPy

In [19]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


### NumPy 转 Tensor

In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [21]:
c = torch.tensor(a)
a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


## 6 Tensor on GPU

In [22]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型